create table if not exists psikolog (
  id bigint generated by default as identity primary key,
  nama text not null,
  psikolog text,
  gelar text,
  no_siap text,
  siap_status text,
  siap_berlaku text,
  no_sipp text,
  sipp_status text,
  sipp_berlaku text,
  layanan text,
  alamat text,
  telepon text,
  kota text default 'Surakarta',
  latitude double precision,
  longitude double precision,
  sumber_data text default 'HIMPSI',
  created_at timestamptz default now()
);

alter table psikolog enable row level security;

create policy "Public read"
  on psikolog for select
  to anon
  using (true);

create policy "Anon insert"
  on psikolog for insert
  to anon
  with check (true);
