-- Create psikolog table for storing psychologist data from IPK Indonesia
-- Run this in Supabase SQL Editor

create table if not exists psikolog (
  id bigint generated by default as identity primary key,
  nama text not null,
  gelar text,
  no_str text,
  str_status text check (str_status in ('aktif', 'tidak_aktif')),
  str_berlaku_hingga date,
  no_sippk text,
  sippk_status text check (sippk_status in ('aktif', 'tidak_aktif')),
  sippk_berlaku_hingga date,
  nama_faskes text,
  alamat_lengkap text,
  kota text,
  provinsi text,
  latitude double precision,
  longitude double precision,
  sumber_data text default 'IPK Indonesia',
  url_detail text,
  last_scraped_at timestamptz default now(),
  is_verified_manual boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Indexes for fast queries
create index if not exists idx_psikolog_kota on psikolog (kota);
create index if not exists idx_psikolog_lat_lng on psikolog (latitude, longitude);
create index if not exists idx_psikolog_str_status on psikolog (str_status);
create index if not exists idx_psikolog_sippk_status on psikolog (sippk_status);

-- Enable Row Level Security
alter table psikolog enable row level security;

-- Allow public read access (only active psychologists)
create policy "Public read psikolog"
  on psikolog for select
  using (
    (str_status = 'aktif' or sippk_status = 'aktif')
  );

-- Allow authenticated users to read all (for admin)
create policy "Authenticated read all"
  on psikolog for select
  to authenticated
  using (true);

-- Allow service role full access (for scraper)
create policy "Service full access"
  on psikolog for all
  to service_role
  using (true)
  with check (true);
